// Central registry of article metadata. Used by each article page and by
// ArticleLayout to build bylines, JSON-LD structured data, and related-article
// cards. Add new articles here first, then create the page component.
export const articles = {
    problemWithEsports: {
        slug: "The-Problem-With-Esports",
        name: "The Problem With Esports",
        category: "Industry",
        title: "The Problem With Esports (And How to Fix It)",
        headline: "The Problem With Esports: Fragmentation Is Holding Competitive Gaming Back",
        dek: "Esports is a billion-dollar industry without a front door. Players, teams, and organizers are scattered across dozens of platforms — and it's slowing everyone down.",
        description: "The current problem with esports today and what uSync.gg is doing to combat this major issue plaguing the industry.",
        image: "https://i.imgur.com/zvYfTtx.jpg",
        imageAlt: "Esports arena filled with fans watching a competitive gaming match",
        imageCredit: "World Economic Forum",
        thumb: "https://i.imgur.com/vBqSUhI.png",
        datePublished: "2026-01-28",
        dateModified: "2026-07-11",
        readTime: 4,
        keywords: ["esports fragmentation", "how to join an esports tournament", "esports platform", "LANs near me", "esports community"],
    },

    howWeFixIt: {
        slug: "How-We-Fix-It",
        name: "How We Fix It",
        category: "Platform",
        title: "How uSync Fixes Esports Fragmentation",
        headline: "How uSync Fixes the Problem With Esports",
        dek: "One platform for leagues, LANs, tournaments, and wagers — here's how uSync brings a fragmented industry under one roof.",
        description: "uSync is unifying the entire esports landscape. Find out how you can be a part of this ever growing opportunity.",
        image: "https://i.imgur.com/TTV0RZS.jpg",
        imageAlt: "Competitive esports players at a live tournament event",
        imageCredit: "World Economic Forum",
        thumb: "https://i.imgur.com/Q6NQGsD.png",
        datePublished: "2026-01-28",
        dateModified: "2026-07-11",
        readTime: 4,
        keywords: ["centralized esports hub", "find esports tournaments", "local esports tournaments", "esports leagues", "LAN events"],
    },

    whatWeProvide: {
        slug: "What-We-Provide",
        name: "What We Provide",
        category: "Platform",
        title: "What uSync Provides: Every Esports Event in One Hub",
        headline: "What uSync Provides for Esports",
        dek: "Tournaments, LANs, leagues, wagers, and verified hosts — a breakdown of everything you'll find on uSync.",
        description: "uSync is a one-stop hub for all esports events across the globe. Find tournaments, LANs, leagues, and much more all in one place.",
        image: "https://i.imgur.com/7MQUXKl.jpg",
        imageAlt: "Esports gaming setup with tournament players competing on PCs",
        imageCredit: "ViewSonic",
        thumb: "https://i.imgur.com/Fr7yPnN.png",
        datePublished: "2026-01-28",
        dateModified: "2026-07-11",
        readTime: 4,
        keywords: ["esports hub", "verified esports hosts", "esports tournaments", "LAN tournaments", "esports wagers"],
    },

    joiningEsportsLeague: {
        slug: "How-to-Join-an-Esports-League",
        name: "How to Join an Esports League",
        category: "Guides",
        title: "How to Join an Esports League: Complete Guide",
        headline: "How to Join an Esports League: A Complete Guide",
        dek: "Step-by-step instructions for joining competitive leagues in Call of Duty, Rocket League, Valorant, Warzone, CS2, Halo Infinite, and League of Legends.",
        description: "Learn how to join an esports league, where to find them, and what to do once you're in one. Find your next esports league today.",
        image: "https://i.imgur.com/Jr6Iq9h.jpg",
        imageAlt: "Esports team competing in a professional league match on stage",
        imageCredit: "Game Rant",
        thumb: "https://i.imgur.com/zS2wj8d.png",
        datePublished: "2026-01-28",
        dateModified: "2026-07-11",
        readTime: 7,
        keywords: ["how to join an esports league", "COD leagues", "Valorant leagues", "Rocket League leagues", "CS2 leagues", "Halo Infinite leagues", "League of Legends leagues"],
    },

    howEsportsCanBeBetter: {
        slug: "How-Esports-Can-Be-Better",
        name: "How Esports Can Be Better",
        category: "Industry",
        title: "How Esports Can Be Better",
        headline: "How Esports Can Be Better: Transforming the Community and the Industry",
        dek: "Competitive gaming is bigger than ever, but barriers still hold the community back. A centralized platform can change that.",
        description: "How can esports be better? Centralizing a hub for all of esports to unify the community one step at a time.",
        image: "https://i.imgur.com/4lgBfVg.jpg",
        imageAlt: "Live esports broadcast production at a major gaming event",
        imageCredit: "Live Production",
        thumb: "https://i.imgur.com/DEB6G8p.png",
        datePublished: "2026-01-28",
        dateModified: "2026-07-11",
        readTime: 4,
        keywords: ["how esports can be better", "esports community", "centralized esports platform", "esports events", "competitive gaming"],
    },
};

export const articleList = Object.values(articles);
